### ISSUE TITLE
Authoritative version

### ISSUE THREAD

**Issue by aficustree** [m-lab/ndt-cloud#47]
Hi,

I was exploring different tools to help my organization better guide users in the diagnosis of various 'connectivity' problems (that quite often are not related to connectivity). We ran across NDT and the MLAB site and found it generally aligned to what we were trying to do. Apologies for the dumb questions but hoped you might be able to provide a bit of context as the readme.md was still a little sparse. 

1. Is the m-lab fork of ndt considered the more authoritative version (as it seems to be more updated)?
2. is ndt-cloud a rewrite with more modern approaches or is it fundamentally changing anything about NDT?
3. I was a bit unclear on the BRR bits. If our purpose is to try and provide a representative view on performance and most of our fleet does not use BRR, should we avoid the user of BRR in our NDT Server or does the NDT Server get something out of BRR itself that helps with diagnosis of issues?

**Comment by pboothe** [comment]
Hello!

So, M-Lab is in the middle of moving things around, so our repos are a little confused right now, and your question is very apropos.

1. NDT is both a protocol and a codebase. They were developed together by folkas affiliated with the Internet2 project, and the root codebase can currently be found at https://github.com/ndt-project/ndt . The version of the code that is deployed on M-Lab's servers can be found at https://github.com/m-lab/ndt . We try to remember to submit all our changes upstream, but there is frequently a lag. The protocol is the same between those two repos.

2. ndt-cloud is a new codebase that speaks the NDT protocol and a new protocol called ndt7. It is intended to support old clients without change via the code under the `legacy` subdirectory. At the same time, researcher @bassosimone is writing a new version of the ndt protocol that vastly simplifies things on both sides and is more "web-native". The server he is writing can be found in the `ndt7` subdirectory. (We chose ndt7 because ndt6 was two easily confused as being something about ipv6). That server doesn't change the single-stream nature of the test, but the ndt7 protocol incompatible with the `legacy` NDT protocol.

3. BBR is a complicated subject, but the shortest version is: Thanks to [RFC 8337](https://tools.ietf.org/html/rfc8337), if you want to be able to compare measurements to M-Lab with measurements to your network then using BBR-based measurements makes that job as easy as possible.  BBR ends up constructing an explicit model of the network, and assessing Bottleneck Bandwidth and Round-trip-time as fundamental measurement outputs. This means that it aids in issue diagnosis by providing metrics that are much more explicit about network properties than the metrics provided by older TCP stacks. Even if you don't use BBR for content serving, single-stream BBR-based measurements are likely the right thing for you.

The ndt-cloud codebase mostly works today, but as you can see from its code history it is under active development. I would recommend, if you want to deploy an NDT server on your network today, that you use the docker image `pboothe/ndt-cloud`, which (and I'm sorry about this confusion - the name of the image was chosen before we named the ndt-cloud repo) is the original NDT binary packed with all of the pieces that require kernel modifications chopped out. In 2019Q1, we anticipate deploying the m-lab/ndt-cloud repo to production and then I will feel safe advocating for its use by others, but right now it suffers from pretty high churn.

**Comment by aficustree** [comment]
Super helpful. Thank you! 

So do I have this right...if we wanted to start something today, we would likely be safe to use the dockerized version of the legacy codebase amusingly titled pboothe/ndt-cloud and would use the HTML5/JS example in the NDT code base to build a web front-end to allow users to self-run tests against that dockerized server. As the /m-lab/ndt-cloud codebase settles down, we could port our backend into this version and adjust our front-end tests in due-course.

**Comment by pboothe** [comment]
Precisely! The timeline for the full deployment of this repo is in Q1 next year, which means that in March you will likely start wanting to care about porting your client to the (much, much simpler) ndt7 protocol.
